workflows:
  workflow:
    name: Build, test, and publish
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      flutter: 3.19.3
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*master*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Test
        script: flutter test
      - name: Build
        script: flutter build apk
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo 'Post-publish script'