---
workflows:
  workflow:
    name: Build, test, and publish
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - github_creds
      android_signing:
        - android-keystore
      # vars:
      #   GITHUB_TOKEN
      flutter: 3.19.3
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Test
        script: flutter test
      - name: Build
        script: flutter build apk
        ignore_failure: false
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      scripts:
        - name: Release to github
          script: | 
            #!/usr/bin/env zsh

            # Publish only for tag builds
            if [ -z ${CM_TAG} ]; then
              echo "Not a tag build, will not publish GitHub release"
              exit 0
            fi

            gh release create "${CM_TAG}" \
              --title "Pokemon ${CM_TAG}" \
              --notes-file changelog.md \
              build/**/outputs/apk/**/*.apk